### PR TITLE
DynamicProperty of optional property

### LINKED ISSUE #3547: DynamicProperty of optional property: Fatal error on force unwrap
Consider the following snippet:

```
class MyObject: NSObject {
    @objc dynamic var name: String?

    init(name: String) {
        self.name = name
    }
}

let object = MyObject(name: "Joe")

let dynamicProperty = DynamicProperty<String?>(object: object, keyPath: "name")
dynamicProperty.producer.startWithValues { print("Dynamic: \($0)")}
object.name = "Jack"
object.name = nil
```

When setting the property to nil, the following crash occurs 
> Fatal error: Unexpectedly found nil while unwrapping an Optional value

in [NSObject+KeyValueObserving.swift:79](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/NSObject%2BKeyValueObserving.swift#L79)

```
init(object: NSObject, keyPath: String) {
  self.producer = object.reactive.producer(forKeyPath: keyPath).map { $0 as! Value }
}
```

This was introduced in #3461 that was intended to strip the optionality of DynamicProperty - but what about DynamicProperties that are Optional to begin with?

### PR DESCRIPTION
**Pull request by iv-mexx**
#### Checklist
- [x] Updated CHANGELOG.md.

Adds necessary overloads to `DynamicProperty` and `Property` to enable the usage with optional `Value`. 

Refs #3547.

### CODE REVIEW

File: ReactiveCocoa/DynamicProperty.swift [hunk 1]
```diff
@@ -45,16 +45,42 @@ public final class DynamicProperty<Value>: MutablePropertyProtocol {
...
+	public convenience init(object: NSObject, keyPath: String) {
+		self.init(object: object, keyPath: keyPath, cache: Property(object: object, keyPath: keyPath))
+	}
+}
+
+extension DynamicProperty where Value: OptionalProtocol {
+	
+	/// The current value of the property, as read and written using Key-Value
+	/// Coding.
+	public var value: Value {
```
Comment (andersio) [inline ReactiveCocoa/DynamicProperty.swift]: Not quite sure why this needs to be overriden.

File: ReactiveCocoa/NSObject+KeyValueObserving.swift [hunk 2]
```diff
@@ -55,6 +55,34 @@ extension Reactive where Base: NSObject {
...
+	///   - keyPath: The key path to observe.
+	public convenience init(object: NSObject, keyPath: String) {
+		// `Property(_:)` caches the latest value of the `DynamicProperty`, so it is
+		// saved to be used even after `object` deinitializes.
+		self.init(UnsafeOptionalKVOProperty(object: object, keyPath: keyPath))
+	}
+	
+	// `Property(unsafeProducer:)` is private to ReactiveSwift. So the fact that
+	// `Property(_:)` uses only the producer is explioted here to achieve the same effect.
+	private final class UnsafeOptionalKVOProperty: PropertyProtocol {
```
Comment (andersio) [inline ReactiveCocoa/NSObject+KeyValueObserving.swift]: `UnsafeKVOProperty` can be shared, since the only thing different is the transform.

File: ReactiveCocoa/DynamicProperty.swift (hunk 1 above)
Comment (iv-mexx) [reply ReactiveCocoa/DynamicProperty.swift]: I don't know why it happens, but otherwise the `should write the underlying object` Testcase fails with:

> expected to be nil, got <<null>>

Comment (andersio) [reply ReactiveCocoa/DynamicProperty.swift]: I am a bit skeptical if this overload is called in a generic context (`MutablePropertyProtocol` specifically) though.

File: ReactiveCocoa/NSObject+KeyValueObserving.swift (hunk 2 above)
Comment (iv-mexx) [reply ReactiveCocoa/NSObject+KeyValueObserving.swift]: Alright, I've changed that

File: ReactiveCocoa/DynamicProperty.swift (hunk 1 above)
Comment (iv-mexx) [reply ReactiveCocoa/DynamicProperty.swift]: Is ae79efb what you meant?

Comment (andersio) [reply ReactiveCocoa/DynamicProperty.swift]: Yep. Looks nice.
