### PR TITLE
Moved flatMapError to Signal

### LINKED ISSUE #2414: Signal<AnyObject, NSError> to Signal<AnyObject, NoError>?
We have `catch` (or `flatMapError` now in RAC4) for converting a `SignalProducer` that sends `NSError` to `NoError`. How would you do the same with a `Signal`? I see `mapError` but as far as I can tell, it's not possible to use that operator to achieve this? Or am I wrong? 😳

### PR DESCRIPTION
**Pull request by NachoSoto**
Fixes #2414.

### CODE REVIEW

File: ReactiveCocoa/Swift/Signal.swift [hunk 1]
```diff
@@ -229,6 +229,33 @@ extension SignalType {
 		}
 	}
 
+	/// Catches any failure that may occur on the input signal, mapping to a new producer
```
Comment (neilpa) [inline ReactiveCocoa/Swift/Signal.swift]: mapping to a new **signal**

Comment (neilpa) [inline ReactiveCocoa/Swift/Signal.swift]: nevermind
