### PR TITLE
[Swift 2] Fix preprocessor directive for iOS build

### LINKED ISSUE #2216: Carthage update Xcode Beta 4
When I do:

```
carthage update --platform ios
```

I am getting loads of warnings in the following format:

```
<module-includes>:1:1: warning: umbrella header for module 'ReactiveCocoa' does not include header 
'/Users/ruiperes/Documents/Project/X/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Objective-C/MKAnnotationView+RACSignalSupport.h'
.
.
.
```

Once inside the project:

screen shot 2015-07-24 at 23 55 42

On the cartfile: `github "reactivecocoa/ReactiveCocoa" "swift2"`

### PR DESCRIPTION
**Pull request by ikesyo**
Fixes #2216.

```objc
#ifdef TARGET_OS_WATCH
#elif defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
```

does not work well.

### CODE REVIEW

**Comment by MarcoSero** [comment]
Thank you for taking care of this :bow:

File: ReactiveCocoa/ReactiveCocoa.h [hunk 1]
```diff
@@ -62,8 +62,8 @@ FOUNDATION_EXPORT const unsigned char ReactiveCocoaVersionString[];
 #import <ReactiveCocoa/RACTuple.h>
 #import <ReactiveCocoa/RACUnit.h>
 
-#ifdef TARGET_OS_WATCH
-#elif __IPHONE_OS_VERSION_MIN_REQUIRED
+#if TARGET_OS_WATCH
```
Comment (ikesyo) [inline ReactiveCocoa/ReactiveCocoa.h]: This is the same way as `TARGET_OS_MAC` of [this line](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2218/files#diff-8fad1d07697f66d8d17da19478832e4fR86).

**Comment by ikesyo** [comment]
Added another commit: 4a97005

**Comment by neilpa** [comment]
:+1:
