### PR TITLE
Fixed a `Lifetime` related KVO crash.

### LINKED ISSUE #3329: Crash when using reactive.values(forKeyPath:)
It looks like `reactive.values(forKeyPath:)` crashes when it tries to remove observers after the observed object is deallocated.

Library versions:

ReactiveSwift: 1.0.0-alpha.3
ReactiveCocoa: 5.0.0-alpha.3

Events:

```
[] starting fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(0) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] started fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(0) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(0) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(0) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(1) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] value Optional(1) fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] completed fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
[] terminated fileName: Radiant/ExportCommaSeparatedDataOperation.swift, functionName: init(realmURL:successHandler:errorHandler:), lineNumber: 45
```

Exception:

```
2016-12-05 12:41:29.206 Radiant[74054:19304036] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ReactiveCocoa.KeyValueObserver 0x600000c74bc0> for the key path "isFinished" from <Radiant.ExportCommaSeparatedDataOperation 0x6000004831b0> because it is not registered as an observer.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e8b634b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010e31721e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e91f265 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010de313c8 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 493
	4   Foundation                          0x000000010de31182 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   Foundation                          0x000000010de938b3 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:context:] + 177
	6   ReactiveCocoa                       0x0000000110f0388f _TFZFC13ReactiveCocoa16KeyValueObserver7observeFTCSo8NSObject7keyPathSS7optionsVSC26NSKeyValueObservingOptions6actionFGSqPs9AnyObject__T__C13ReactiveSwift16ActionDisposableU2_FT_T_ + 143
	7   ReactiveSwift                       0x0000000110f5eefe _TTRXFo___XFo_iT__iT__ + 14
	8   ReactiveSwift                       0x0000000110f7c140 _TPA__TTRXFo___XFo_iT__iT__ + 64
	9   ReactiveSwift                       0x0000000110f7d5ee _TPA__TTRXFo___XFo_iT__iT__.11 + 14
	10  ReactiveSwift                       0x0000000110f799f2 _TFC13ReactiveSwift16ActionDisposable7disposefT_T_ + 130
	11  ReactiveSwift                       0x0000000110f5ef56 _TTWC13ReactiveSwift16ActionDisposableS_10DisposableS_FS1_7disposefT_T_ + 22
	12  ReactiveSwift                       0x0000000110f7ef1f _TFFV13ReactiveSwift14SignalProducer15startWithSignalFFTGCS_6Signalxq__PS_10Disposable__T_T_U_FT_T_ + 255
	13  ReactiveSwift                       0x0000000110f5eefe _TTRXFo___XFo_iT__iT__ + 14
	14  ReactiveSwift                       0x0000000110f91e40 _TPA__TTRXFo___XFo_iT__iT__ + 64
	15  ReactiveSwift                       0x0000000110f799f2 _TFC13ReactiveSwift16ActionDisposable7disposefT_T_ + 130
	16  ReactiveSwift                       0x0000000110f5ef56 _TTWC13ReactiveSwift16ActionDisposableS_10DisposableS_FS1_7disposefT_T_ + 22
	17  ReactiveSwift                       0x0000000110f7f18f _TFFV13ReactiveSwift14SignalProducer15startWithSignalFFTGCS_6Signalxq__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 527
	18  ReactiveSwift                       0x0000000110f4911a _TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 2026
	19  ReactiveSwift                       0x0000000110f49536 _TPA__TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 118
	20  ReactiveSwift                       0x0000000110f5058b _TFFFE13ReactiveSwiftPS_14SignalProtocol2onFT5eventGSqFGOS_5Eventwx5Valuewx5Error_T__6failedGSqFwxS3_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__5valueGSqFwxS2_T___GCS_6SignalwxS2_wxS3__U_FGCS_8ObserverQQPS0_5ValueQS6_5Error_GSqPS_10Disposable__U_FGS1_S7_S8__T_ + 1147
	21  ReactiveSwift                       0x0000000110f77390 _TPA__TFFFE13ReactiveSwiftPS_14SignalProtocol2onFT5eventGSqFGOS_5Eventwx5Valuewx5Error_T__6failedGSqFwxS3_T__9completedGSqFT_T__11interruptedGSqFT_T__10terminatedGSqFT_T__8disposedGSqFT_T__5valueGSqFwxS2_T___GCS_6SignalwxS2_wxS3__U_FGCS_8ObserverQQPS0_5ValueQS6_5Error_GSqPS_10Disposable__U_FGS1_S7_S8__T_ + 336
	22  ReactiveSwift                       0x0000000110f4911a _TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 2026
	23  ReactiveSwift                       0x0000000110f49536 _TPA__TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 118
	24  ReactiveSwift                       0x0000000110f7f064 _TFFV13ReactiveSwift14SignalProducer15startWithSignalFFTGCS_6Signalxq__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 228
	25  ReactiveSwift                       0x0000000110fa0489 _TFC13ReactiveSwift8Observer15sendInterruptedfT_T__merged + 105
	26  ReactiveCocoa                       0x0000000110f05cee _TPA__TFC13ReactiveSwift8Observer13sendCompletedfT_T_ + 14
	27  ReactiveSwift                       0x0000000110f6d06f _TPA__TTRGRx13ReactiveSwift14SignalProtocolrXFo___XFo_iT__iT__ + 47
	28  ReactiveSwift                       0x0000000110fa0915 _TFFC13ReactiveSwift8ObservercFT5valueGSqFxT__6failedGSqFq_T__9completedGSqFT_T__11interruptedGSqFT_T___GS0_xq__U_FGOS_5EventQ_Q0__T_ + 245
	29  ReactiveSwift                       0x0000000110fa0b61 _TPA__TFFC13ReactiveSwift8ObservercFT5valueGSqFxT__6failedGSqFq_T__9completedGSqFT_T__11interruptedGSqFT_T___GS0_xq__U_FGOS_5EventQ_Q0__T_ + 225
	30  ReactiveSwift                       0x0000000110f6a1fc _TTSf4n_g_g_g___TTSg5T__O6Result7NoErrorS0_s5ErrorS____TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 460
	31  ReactiveSwift                       0x0000000110f91c8b _TTSr5T__O6Result7NoErrorS0_s5ErrorS____TFFC13ReactiveSwift6SignalcFFGCS_8Observerxq__GSqPS_10Disposable__GS0_xq__U_FGOS_5EventQ_Q0__T_ + 27
	32  ReactiveSwift                       0x0000000110fab5af _TFCC13ReactiveSwift8Lifetime5TokenD + 47
	33  libobjc.A.dylib                     0x000000010e3260c3 _object_remove_assocations + 375
	34  libobjc.A.dylib                     0x000000010e3214ea objc_destructInstance + 141
	35  libobjc.A.dylib                     0x000000010e321510 object_dispose + 22
	36  Foundation                          0x000000010de1befb -[NSOperation dealloc] + 89
	37  Radiant                             0x000000010dc1bc9c _TFC7Radiant33ExportCommaSeparatedDataOperationD + 204
	38  Radiant                             0x000000010dc1bd42 _TToFC7Radiant33ExportCommaSeparatedDataOperationD + 34
	39  Foundation                          0x000000010de4d2fa NSKVODeallocate + 94
	40  libobjc.A.dylib                     0x000000010e32bb12 _ZN11objc_object17sidetable_releaseEb + 212
	41  libobjc.A.dylib                     0x000000010e32c1d1 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 715
	42  libdispatch.dylib                   0x0000000113aa90cd _dispatch_client_callout + 8
	43  libdispatch.dylib                   0x0000000113a86e6b _dispatch_queue_serial_drain + 236
	44  libdispatch.dylib                   0x0000000113a87b9f _dispatch_queue_invoke + 1073
	45  libdispatch.dylib                   0x0000000113a8a3b7 _dispatch_root_queue_drain + 720
	46  libdispatch.dylib                   0x0000000113a8a08b _dispatch_worker_thread3 + 123
	47  libsystem_pthread.dylib             0x0000000113e58736 _pthread_wqthread + 1299
	48  libsystem_pthread.dylib             0x0000000113e58211 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### PR DESCRIPTION
**Pull request by andersio**
Fixes #3329.

`Lifetime` deallocates too late in the deallocation chain - literally before KVO observation info is verified, and the memory is released. It _somehow_ causes issues when using the KVO API with `Operation`. So [let's follow ReactiveObjC and have `-dealloc` swizzled](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/580).

Implementation Notes
1. ~~`_racLifetimeNewDeallocImplementation` cannot be implemented in Swift AFAICT, as Swift does not respect the `__unsafe_unretained` label and would insert retain/release calls. While it does not matter in #3302, it messes with the ObjC deallocation chain in this case. `objc_msgSendSuper` also somehow does not behave as intended...~~
2. We need to know "perceived class" instead of the runtime real class, as KVO's `-dealloc` cannot be swizzled (somehow). `-class` is the thing, but it is unavailable in Swift. `type(of:)` returns the runtime subclasses. So the `AnyObject` message sending is used (also in #3302).
3. Managed to almost implement it completely in Swift, except that it needs a trampoline for `objc_setAssociatedObject` to avoid ARC retain and release on the object. Apparently when imported to Swift it has been wrapped with a thunk which inserted the calls.

The method can be moved to the runtime subclass after #3302 is landed.

### CODE REVIEW

File: ReactiveCocoa/NSObject+Lifetime.swift [hunk 1]
```diff
@@ -15,10 +15,53 @@ extension Reactive where Base: NSObject {
...
+					unsafeBitCast(impl, to: Impl.self)(objectRef, deallocSelector)
+				}
+
+				let newImpl =  imp_implementationWithBlock(newImplBlock as Any)
+
+				if !class_addMethod(objcClass, deallocSelector, newImpl, "v@:") {
+					// The class has an existing `dealloc`. Preserve that as `existingImpl`.
+					let deallocMethod = class_getInstanceMethod(objcClass, deallocSelector)
+					existingImpl = method_getImplementation(deallocMethod)
+					existingImpl = method_setImplementation(deallocMethod, newImpl)
```
Comment (mdiep) [inline ReactiveCocoa/NSObject+Lifetime.swift]: We probably don't need to set `existingImpl` twice—which means we could get rid of the call to `method_getImplementation`.

File: ReactiveCocoa/NSObject+Lifetime.swift [hunk 2]
```diff
@@ -15,10 +15,53 @@ extension Reactive where Base: NSObject {
...
 
 			return lifetime
 		}
 	}
 }
+
+@objc private protocol ObjCClassReporting {
+	@objc(class)
+	var objcClass: AnyClass { get }
+}
```
Comment (mdiep) [inline ReactiveCocoa/NSObject+Lifetime.swift]: Why is this needed? Can you add a comment?

File: ReactiveCocoa/NSObject+Lifetime.swift [hunk 3]
```diff
@@ -15,10 +15,53 @@ extension Reactive where Base: NSObject {
...
+			// Swizzle `-dealloc` so that the lifetime token is released at the
+			// beginning of the deallocation chain, and only after the KVO `-dealloc`.
+			objc_sync_enter(objcClass)
+			if objc_getAssociatedObject(objcClass, &lifetimeKey) == nil {
+				objc_setAssociatedObject(objcClass, &lifetimeKey, true, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
+
+				var existingImpl: IMP? = nil
+
+				let newImplBlock: @convention(block) (UnsafeRawPointer) -> Void = { objectRef in
+					_rac_objc_setAssociatedObject(objectRef, &lifetimeTokenKey, nil, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
```
Comment (mdiep) [inline ReactiveCocoa/NSObject+Lifetime.swift]: Would it make more sense to close over a local `Lifetime.Token?` variable instead of using an associated object here? If we're explicitly deallocating, then we don't seem to get any actual benefit from storing it as an associated object.

File: ReactiveCocoa/RACObjCRuntimeUtilities.h [hunk 4]
```diff
@@ -1,6 +1,9 @@
 #import <Foundation/Foundation.h>
+#import <objc/runtime.h>
 
 NS_ASSUME_NONNULL_BEGIN
+void _rac_objc_setAssociatedObject(const void* object, const void* key, id _Nullable value, objc_AssociationPolicy policy);
```
Comment (mdiep) [inline ReactiveCocoa/RACObjCRuntimeUtilities.h]: This could use documentation about why it's necessary (if we continue to use it).

File: ReactiveCocoaTests/KeyValueObservingSpec.swift [hunk 5]
```diff
@@ -154,6 +154,19 @@ class KeyValueObservingSpec: QuickSpec {
 				expect(weakOriginalInner).to(beNil())
 			}
 
+			describe("special tests") {
```
Comment (mdiep) [inline ReactiveCocoaTests/KeyValueObservingSpec.swift]: This `describe` is probably not needed—I think the `it` could be at the same level as the others.

File: ReactiveCocoa/NSObject+Lifetime.swift (hunk 1 above)
Comment (andersio) [inline ReactiveCocoa/NSObject+Lifetime.swift]: It is intentional, because while the call itself is thread safe, these calls could in theory race with invocations and other swizzling frameworks. So setting it the first time is to ensure there is at least an implementation, and setting it the second time is to ensure it is up-to-date.

Maybe I should have brought over the comments too.

File: ReactiveCocoa/NSObject+Lifetime.swift (hunk 3 above)
Comment (andersio) [inline ReactiveCocoa/NSObject+Lifetime.swift]: The block is an implementation that is shared across all instances.

File: ReactiveCocoa/NSObject+Lifetime.swift (hunk 2 above)
Comment (andersio) [inline ReactiveCocoa/NSObject+Lifetime.swift]: > We need to know "perceived class" instead of the runtime real class, as KVO's -dealloc cannot be swizzled (somehow). -class is the thing, but it is unavailable in Swift. type(of:) returns the runtime subclasses. So the AnyObject message sending is used (also in #3302).

Comment (andersio) [inline ReactiveCocoa/NSObject+Lifetime.swift]:
```swift
let objcClass: AnyClass = (base as AnyObject).objcClass
```

File: ReactiveCocoa/NSObject+Lifetime.swift [hunk 6]
```diff
@@ -15,10 +15,71 @@ extension Reactive where Base: NSObject {
...
+
+				var existingImpl: IMP? = nil
+
+				let newImplBlock: @convention(block) (UnsafeRawPointer) -> Void = { objectRef in
+					// A custom trampoline of `objc_setAssociatedObject` is used, since
+					// the imported version has been inserted with ARC calls that would
+					// mess with the object deallocation chain.
+
+					// Release the lifetime token.
+					_rac_objc_setAssociatedObject(objectRef, &lifetimeTokenKey, nil, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
```
Comment (mdiep) [inline ReactiveCocoa/NSObject+Lifetime.swift]: What I meant about this was that it seems like we could do this:

```swift
var token: Lifetime.Token? = Lifetime.Token()
let lifetime = Lifetime(token)

...

if objc_getAssociatedObject(objcClass, &lifetimeKey) == nil {
    objc_setAssociatedObject(objcClass, &lifetimeKey, true, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)

    var existingImpl: IMP? = nil

    let newImplBlock: @convention(block) (UnsafeRawPointer) -> Void = { objectRef in
        // Release the lifetime token.
        token = nil

        ...
    }

    ...
}
```

Comment (andersio) [inline ReactiveCocoa/NSObject+Lifetime.swift]: As I said, the block is an implementation that is shared across all instances of the class. Unless you create a subclass for each instance at runtime, this would not work.

Comment (mdiep) [inline ReactiveCocoa/NSObject+Lifetime.swift]: Oh, duh. Dunno what I was thinking. I guess I got confused between associated objects on the instance and on the class. 🙃
